# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bf6d26cb265c939c6ee8ea1a5a04665017e3b3b395af6e5014436e5fa8ecfbe7f739ed6c22f5bda82e69cd14250ebb230e4a91acfa611aa3767961fec166fab

test:
  secret_key_base: e5e7b8bce1334e4b12551d6788d7f7ef52d25151eb8c7dc3b8e2662a78d1aa12fe1e7eb8834507cd1c522b4c35d07f56eeadd93f19a34ade281059958f79f8af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
